### ISSUE TITLE
Build for officially not supported device (crackling)

### ISSUE THREAD

**Issue by ialokim** [crdroid-devices/build_crDroid#3]
For the wileyfox swift (crackling), there were some crDroid builds until 2019 [available on XDA-Developers](https://forum.xda-developers.com/wileyfox-swift/rom-crdroid-android-5-0-t3852616). Unfortunately, it seems these have never been official and the contributors beroid and @neobuddy89 didn't provide new versions anymore.

However I've seen the crackling device is [officially supported by LineageOS](https://wiki.lineageos.org/devices/crackling). As crDroid builds on top of LOS, how easy or difficult would it be to build crDroid for this device using the LOS [device configuration](https://github.com/LineageOS/android_device_wileyfox_crackling) and [kernel](https://github.com/LineageOS/android_kernel_cyanogen_msm8916)? How would one proceed? Would it be sufficient to follow the [LOS build instructions](https://wiki.lineageos.org/devices/crackling/build), but checking out the crDroid sources instead?

**Comment by gwolf2u** [comment]
Pretty much no changes needed unless for some crDroid specific overlays let's say
But for a start, no need to change anything
