### ISSUE TITLE
How to upload to SourceForge (SFTP)?

### ISSUE THREAD

**Issue by akash07k** [crdroid-devices/build_crDroid#5]
First of all,
Really thanks a lot for this wonderful script.
Actually I want to automatically upload my builds to my sourceforge.
However, even after entering all the values, uploading fails.
The reason is it tries to connect on port 21, whereas SFTP works on port 22.
I tried to manually change the port in build script but seems it is not hard coded anywhere.
Please help

**Comment by gwolf2u** [comment]
You need to modify the script to use rsync or maybe lftp or so since with curl, we use ftp (port 21 default)
The script is designed to work with our infra, that accepts ftp upload to SF
